-- ============================================================================
-- Herval AI · tabela de agendamentos
--
-- >>> JÁ EXECUTADO no banco em 30/09/2026. Este arquivo é o registro do que foi
-- >>> rodado, não uma pendência. É repetível: rodar de novo não recria nada.
-- ============================================================================
--
-- Cria a tabela que faltava para a Agenda existir de verdade. Até aqui a tela
-- lia um arquivo fixo e vazio no código: marcar uma consulta mudava a memória
-- do navegador e sumia ao recarregar a página.
--
-- Um agendamento é o ato de marcar uma consulta. O mesmo lead pode ter mais de
-- um: remarcou, conta de novo, e o histórico de quem faltou continua lá. Nada
-- no banco impede duas consultas abertas para o mesmo lead — paciente que marca
-- dois procedimentos é coisa que acontece, e a tela não proíbe. Quem cuida de
-- "remarcar substitui" é a ação da tela, não uma restrição aqui.
--
-- As duas datas medem coisas diferentes, e cada relatório usa uma: `criado_em`
-- é quando a equipe marcou (produção da equipe), `data_consulta` é quando o
-- paciente é atendido (movimento do funil).
--
-- Por que `data_consulta` e `hora_consulta`, e não `data` e `hora`: o cliente
-- do Supabase devolve tudo dentro de um campo chamado `data`, e uma coluna com
-- esse nome deixaria o código com `data.data` em toda leitura.
--
-- O lugar é obrigatório e a pessoa não. Quem marca sabe onde o paciente deve
-- aparecer antes de saber com quem — a agência confirma o horário primeiro e
-- distribui na equipe depois. Sem profissional ou sem hora a consulta aparece
-- na tela em "Aguardando horário" em vez de ganhar um horário inventado.
--
-- Não existe coluna de cliente: ele sai da unidade (`unidades.clinica_id`).
-- Guardar os dois deixaria as duas versões divergirem no dia em que alguém
-- corrigisse uma só.
--
-- E não existe nenhuma coluna de valor, aqui nem em lugar nenhum do sistema.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. A tabela
--
-- O que cada `on delete` decide, que é onde mora o risco:
--
--   lead_id          cascade: apagar o lead apaga as consultas dele. Consulta
--                    de lead que não existe não é histórico, é lixo.
--   unidade_id       restrict: apagar uma unidade com consulta marcada é
--                    recusado. Sem isso o histórico de atendimento do lugar
--                    desapareceria em silêncio junto com ele.
--   profissional_id  set null: a pessoa saiu da equipe, a consulta aconteceu.
--                    A consulta fica, sem dono, em vez de ser apagada.
--   especialidade_id set null: mesmo motivo. O catálogo muda, o passado não.
--
-- Não há chave composta para `profissional_unidades` de propósito: a pessoa
-- pode deixar de atender naquele lugar depois de a consulta ter acontecido, e
-- isso não pode apagar nem travar o passado. Que o profissional escolhido
-- atenda naquela unidade é conferido na tela, na hora de marcar.
-- ----------------------------------------------------------------------------
create table if not exists public.agendamentos (
  id bigint generated by default as identity primary key,
  lead_id integer not null references public.leads (id) on delete cascade,
  unidade_id integer not null references public.unidades (id) on delete restrict,
  profissional_id integer references public.profissionais (id) on delete set null,
  especialidade_id integer references public.especialidades (id) on delete set null,
  data_consulta date not null,
  hora_consulta time,
  status text not null default 'Agendada',
  -- O paciente respondeu confirmando presença.
  confirmada boolean not null default false,
  -- Quem travou o agendamento: a IA sozinha ou um atendente do CRC.
  fechado_por text not null default 'CRC',
  -- Recado livre de quem marcou: o que o paciente pediu, o que a clínica
  -- precisa lembrar.
  observacao text,
  criado_em timestamptz not null default now(),
  constraint agendamentos_status_valido
    check (status in ('Agendada', 'Compareceu', 'Faltou', 'Cancelada')),
  constraint agendamentos_fechado_por_valido
    check (fechado_por in ('IA', 'CRC'))
);


-- ----------------------------------------------------------------------------
-- 2. Índices
--
-- A tela abre sempre em uma semana e filtra por unidade; a ficha de um lead
-- pede as consultas dele. São os três caminhos que existem.
-- ----------------------------------------------------------------------------
create index if not exists agendamentos_por_dia
  on public.agendamentos (data_consulta);

create index if not exists agendamentos_por_unidade_e_dia
  on public.agendamentos (unidade_id, data_consulta);

create index if not exists agendamentos_por_lead
  on public.agendamentos (lead_id);


-- ----------------------------------------------------------------------------
-- 3. Quem pode ler e gravar
--
-- Mesmo desenho de `unidades` e `profissional_unidades`: RLS ligada, uma
-- política para quem está autenticado, e a chave pública (`anon`) sem nenhum
-- privilégio — a política já barraria, mas privilégio revogado é a barreira
-- que não depende de ninguém escrever a política certa.
--
-- TRUNCATE sai à parte porque RLS não cobre TRUNCATE: a política filtra linha
-- por linha e o TRUNCATE não olha linha nenhuma. Sem este revoke, uma chave
-- autenticada esvaziaria a tabela inteira com um comando.
-- ----------------------------------------------------------------------------
alter table public.agendamentos enable row level security;

drop policy if exists "Autenticado le e grava" on public.agendamentos;
create policy "Autenticado le e grava" on public.agendamentos
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

revoke all on public.agendamentos from anon;
revoke truncate on public.agendamentos from authenticated;


-- ----------------------------------------------------------------------------
-- 4. O painel passa a poder registrar mudança de etapa
--
-- `lead_etapa_eventos` tinha só política de leitura. Quem escrevia nela era o
-- cérebro no n8n, que entra como dono da tabela e não passa por política
-- nenhuma. Agora a Agenda também move o lead de etapa — quem comparece vai para
-- "Comparecimento", quem falta cai em "Reagendamento" — e sem esta política a
-- linha do histórico seria recusada em silêncio: a etapa mudaria e ninguém
-- saberia quem mudou.
--
-- O `with check` é o mesmo desenho de `notas`: a linha tem que ser assinada por
-- quem está gravando. Ninguém registra mudança no nome de outra pessoa.
-- ----------------------------------------------------------------------------
drop policy if exists "Equipe registra mudanca de etapa" on public.lead_etapa_eventos;
create policy "Equipe registra mudanca de etapa" on public.lead_etapa_eventos
  for insert
  with check (auth.uid() = autor_id);
