-- ============================================================================
-- Herval AI · notas do CRC e histórico de etapas
-- Cole este arquivo inteiro no SQL Editor do Supabase e clique em "Run".
-- Pode rodar mais de uma vez sem quebrar nada.
-- ============================================================================
--
-- Estas duas tabelas não existiam. Até agora as notas e o histórico da tela de
-- atendimento vinham de arquivo fixo (`src/data/notas.ts` e
-- `src/data/historicoEtapas.ts`), iguais para todo mundo e perdidos a cada
-- recarregamento.
--
-- Por que duas tabelas e não uma: nota é texto que uma pessoa escreveu, e
-- mudança de etapa é um fato que o sistema observou. Guardar as duas coisas na
-- mesma tabela obrigaria metade das colunas a ficar sempre vazia.
--
-- O resto da linha de tempo do lead NÃO ganha tabela, de propósito: a chegada
-- do lead já é `leads.criado_em` e cada fala já é uma linha de `mensagens`.
-- Copiar isso para um terceiro lugar criaria duas versões do mesmo fato.
-- ============================================================================


-- ============================================================================
-- 1) Notas internas do CRC
-- ============================================================================
--
-- É uma lista, e não um campo que se reescreve. Nota que se sobrescreve apaga
-- o que a pessoa anterior sabia; aqui dá para dizer sempre quem escreveu o quê
-- e quando.
--
-- `autor_id` aponta para o usuário de autenticação, e `autor_nome` guarda o
-- nome que ele tinha na hora de escrever. Os dois juntos, e não só o id: se a
-- pessoa sair da equipe e o usuário for apagado, a nota continua legível e
-- assinada em vez de virar uma linha anônima.

create table if not exists public.notas (
  id          bigint generated by default as identity primary key,
  lead_id     integer not null references public.leads (id) on delete cascade,
  autor_id    uuid references auth.users (id) on delete set null,
  autor_nome  text not null,
  texto       text not null,
  criado_em   timestamptz not null default now()
);

-- Nota vazia não é nota. A checagem fica no banco, e não só na tela, porque a
-- tela pode ser contornada e o banco não.
alter table public.notas drop constraint if exists notas_texto_nao_vazio;
alter table public.notas add constraint notas_texto_nao_vazio
  check (length(btrim(texto)) > 0);

-- A leitura é sempre "as notas deste lead, da mais recente para a mais antiga".
create index if not exists notas_por_lead on public.notas (lead_id, criado_em desc);

alter table public.notas enable row level security;

-- Quem está logado no painel lê e escreve nota. Não há perfil de acesso
-- separado no produto (um CRC vê o que o outro vê), então a política é essa
-- mesma — o que ela barra é a chave `anon`, que vai no navegador de qualquer
-- visitante não autenticado.
drop policy if exists "Equipe le as notas" on public.notas;
create policy "Equipe le as notas"
  on public.notas
  for select
  to authenticated
  using (true);

drop policy if exists "Equipe escreve nota" on public.notas;
create policy "Equipe escreve nota"
  on public.notas
  for insert
  to authenticated
  with check (auth.uid() = autor_id);

-- Sem política de update nem de delete, de propósito: nota é registro do que
-- se sabia naquele momento. Corrigir uma nota antiga é escrever outra.


-- ============================================================================
-- 2) Histórico de etapas do lead
-- ============================================================================
--
-- `leads.etapa` guarda só onde o lead está agora. Esta tabela guarda como ele
-- chegou lá: cada linha é uma passagem de uma etapa para outra.
--
-- Ela nasce vazia e continua vazia até o painel deixar mudar a etapa de
-- verdade — hoje nada muda etapa, porque a etapa ainda vem de dado fictício.
-- Está sendo criada agora para que, no dia em que isso mudar, o histórico
-- comece a se preencher sozinho, em vez de começar do zero naquele dia.
--
-- `de_etapa` aceita nulo: a primeira linha de um lead é a entrada dele no
-- funil, que não vem de etapa nenhuma.

create table if not exists public.lead_etapa_eventos (
  id          bigint generated by default as identity primary key,
  lead_id     integer not null references public.leads (id) on delete cascade,
  de_etapa    text,
  para_etapa  text not null,
  autor_id    uuid references auth.users (id) on delete set null,
  -- Quem moveu. "Sistema" é uma automação, não uma pessoa — por isso é texto
  -- livre e não uma referência obrigatória a um usuário.
  autor_nome  text not null,
  criado_em   timestamptz not null default now()
);

alter table public.lead_etapa_eventos
  drop constraint if exists lead_etapa_eventos_mudou_de_fato;
alter table public.lead_etapa_eventos add constraint lead_etapa_eventos_mudou_de_fato
  check (de_etapa is null or de_etapa <> para_etapa);

create index if not exists lead_etapa_eventos_por_lead
  on public.lead_etapa_eventos (lead_id, criado_em desc);

alter table public.lead_etapa_eventos enable row level security;

drop policy if exists "Equipe le o historico de etapas" on public.lead_etapa_eventos;
create policy "Equipe le o historico de etapas"
  on public.lead_etapa_eventos
  for select
  to authenticated
  using (true);

-- Sem política de insert para `authenticated`: quem grava aqui é o servidor
-- (service role), junto com a alteração de `leads.etapa`, para as duas coisas
-- nunca discordarem. Gravar pelo navegador permitiria registrar uma mudança
-- que não aconteceu.
