-- ============================================================================
-- Herval AI · seção Profissionais
--
-- >>> JÁ EXECUTADO no banco em 29/09/2026. Este arquivo é o registro do que
-- >>> foi rodado, não uma pendência. Rodar de novo não faz mal (é repetível e
-- >>> não duplica linha), mas não é necessário.
-- ============================================================================
--
-- Cria quatro tabelas novas e NÃO altera a estrutura de nenhuma existente:
--
--   profissionais                a pessoa que atende
--   unidades                     onde o cliente atende (todo cliente tem >= 1)
--   profissional_especialidades  o que ele faz
--   profissional_unidades        onde ele faz, e em que dias e horário
--
-- Vocabulário, para o arquivo não ficar ambíguo depois:
--
--   CLIENTE     = uma linha em `clinicas`. Sempre uma, tenha ele dez unidades
--                 ou nenhuma. É com ele que existe contrato.
--   UNIDADE     = um lugar físico daquele cliente. Todo cliente tem no mínimo
--                 uma, criada junto com ele.
--   PROFISSIONAL= a pessoa que atende numa ou mais unidades.
--
-- A ESTRUTURA de `clinicas`, `especialidades`, `clinica_especialidades`,
-- `leads`, `mensagens` e de qualquer outra tabela que já existe fica intacta:
-- nenhuma coluna criada, alterada ou removida, nenhuma linha alterada.
--
-- Dois passos encostam no que já existe, e é de propósito:
--
--   passo 6  lê `clinicas` para criar a primeira unidade dos clientes que já
--            estão cadastrados. Escreve em `unidades`, tabela nova.
--   passo 7  instala um gatilho em `clinicas` para que criar cliente passe a
--            criar a unidade dele automaticamente. Muda o comportamento de
--            inserções futuras, não a estrutura nem o conteúdo atual.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. profissionais
-- ----------------------------------------------------------------------------
-- `id` é integer, igual a `clinicas` e `especialidades`, porque o painel já
-- trata id de profissional como número em uma dúzia de lugares.
--
-- `ativo` existe em vez de apagar: quando a Agenda existir, uma consulta
-- passada precisa continuar sabendo quem atendeu. Profissional que saiu da
-- clínica vira `ativo = false` e sai das listas, sem sumir do histórico.

create table if not exists public.profissionais (
  id         integer generated by default as identity primary key,
  nome       text        not null check (length(btrim(nome)) > 0),

  -- Lista fechada: 17 cargos, decididos pela Herval. Texto livre aqui viraria
  -- "Dentista", "dentista" e "Dr. dentista" na mesma coluna em três meses.
  -- Incluir um cargo novo depois é uma linha de SQL (alterar esta regra).
  tipo       text        not null check (tipo in (
               'Dentista',
               'Cirurgião Dentista',
               'Dermatologista',
               'Médico',
               'Médico Cirurgião',
               'Médico Esteta',
               'Biomédico',
               'Biomédico Esteticista',
               'Enfermeiro',
               'Enfermeiro Esteta',
               'Nutricionista',
               'Fisioterapeuta',
               'Farmacêutico',
               'Psicólogo',
               'Psiquiatra',
               'Esteticista',
               'Avaliador'
             )),

  -- Conselho de classe: CRM, CRO, CRBM, COREN, CRN, CREFITO, CRF, CRP.
  -- Opcional de propósito: esteticista não tem conselho, e campo obrigatório
  -- forçaria alguém a inventar um número para conseguir salvar.
  registro   text,

  ativo      boolean     not null default true,
  criado_em  timestamptz not null default now()
);

comment on table public.profissionais is
  'A pessoa que atende. Nunca representa um cliente: cliente é linha em clinicas.';


-- ----------------------------------------------------------------------------
-- 2. unidades
-- ----------------------------------------------------------------------------
-- Existe porque "em qual das três unidades este profissional atende" é uma
-- pergunta que, se não for feita na hora do cadastro, não tem como ser
-- recuperada depois: nenhuma migração inventa um dado que ninguém digitou.
--
-- Todo cliente tem no mínimo uma unidade, sempre — inclusive o especialista
-- sozinho que aluga sala. Por padrão ela nasce com o nome do próprio cliente,
-- para que quem tem uma só nunca perceba que o conceito existe. Quando
-- aparecer a segunda, a equipe renomeia a primeira ("Centro") e cadastra a
-- outra ("Zona Sul").
--
-- `endereco` e `cidade` espelham exatamente os campos de mesmo nome em
-- `clinicas`, em vez de um formato novo. Endereço é propriedade de um lugar,
-- não de um contrato — é aqui que ele passa a fazer sentido quando o cliente
-- tem mais de um lugar. `clinicas.endereco` fica intocado: ele está na tela de
-- Estratégia e na aba Clínica do Atendimento, e mexer ali é outra conversa.
--
-- `on delete cascade`: unidade é parte do cliente, não tem sentido sem ele.
-- Isso não abre porta para perder dado real — um cliente que já tem lead não
-- pode ser apagado de jeito nenhum, porque `leads.clinica_id` barra.

create table if not exists public.unidades (
  id         integer generated by default as identity primary key,
  clinica_id integer     not null references public.clinicas (id) on delete cascade,
  nome       text        not null check (length(btrim(nome)) > 0),
  endereco   text,
  cidade     text,
  ativa      boolean     not null default true,
  criado_em  timestamptz not null default now(),

  -- Duas unidades do mesmo cliente com o mesmo nome seriam indistinguíveis na
  -- lista de "onde atende". Clientes diferentes podem ter unidades homônimas.
  unique (clinica_id, nome)
);

comment on table public.unidades is
  'Lugar físico de um cliente. Todo cliente tem no mínimo uma, criada junto com ele.';

create index if not exists unidades_clinica_id_idx
  on public.unidades (clinica_id);


-- ----------------------------------------------------------------------------
-- 3. profissional_especialidades — o que ele atende
-- ----------------------------------------------------------------------------
-- Mesmo formato da `clinica_especialidades` que já existe: chave composta,
-- sem id próprio. A ligação mora só aqui, então nenhuma tela discorda de
-- outra sobre quem atende o quê.

create table if not exists public.profissional_especialidades (
  profissional_id  integer not null references public.profissionais (id) on delete cascade,
  especialidade_id integer not null references public.especialidades (id) on delete cascade,
  primary key (profissional_id, especialidade_id)
);

create index if not exists profissional_especialidades_especialidade_id_idx
  on public.profissional_especialidades (especialidade_id);


-- ----------------------------------------------------------------------------
-- 4. profissional_unidades — onde ele atende, em que dias e horário
-- ----------------------------------------------------------------------------
-- Aponta para UNIDADE, e não para cliente. O cliente continua acessível
-- atravessando `unidades`, então o vínculo não fica guardado em dois lugares
-- para depois divergir.
--
-- Os campos de dia e horário entram agora, ainda sem aparecer na tela de
-- Profissionais, porque a Agenda vai precisar deles e porque este é o lugar
-- certo: horário é do par profissional × unidade. O mesmo médico atende
-- segunda no Centro e terça na Zona Sul — guardar isso no cadastro do
-- profissional seria impossível de responder.
--
-- LIMITE CONHECIDO, declarado de propósito: uma linha por par significa uma
-- janela por unidade. "Segunda e quarta, das 9h às 18h" cabe; "segunda de
-- manhã e quarta à tarde" não. Se a Herval precisar disso, a saída é uma
-- quinta tabela de janelas — e essa é a mudança barata, porque cada linha
-- daqui virá uma linha de lá, sem perguntar nada a ninguém.

create table if not exists public.profissional_unidades (
  profissional_id integer not null references public.profissionais (id) on delete cascade,
  unidade_id      integer not null references public.unidades (id)      on delete cascade,

  -- 1 = segunda … 7 = domingo (padrão ISO, o mesmo que o Postgres usa em
  -- `extract(isodow from data)`, para a Agenda não precisar converter nada).
  dias_semana     smallint[],

  hora_inicio     time,
  hora_fim        time,

  primary key (profissional_id, unidade_id),

  -- Nenhum dia fora de 1..7, e nenhuma lista vazia (vazio e nulo dizendo a
  -- mesma coisa é o começo de um bug de leitura).
  constraint profissional_unidades_dias_validos check (
    dias_semana is null
    or (cardinality(dias_semana) > 0
        and dias_semana <@ array[1,2,3,4,5,6,7]::smallint[])
  ),

  -- Hora de início e de fim andam juntas: as duas ou nenhuma.
  constraint profissional_unidades_horario_completo check (
    (hora_inicio is null) = (hora_fim is null)
  ),

  -- Fim depois do início. Barra o 18h–9h digitado ao contrário.
  constraint profissional_unidades_horario_coerente check (
    hora_inicio is null or hora_fim > hora_inicio
  )
);

create index if not exists profissional_unidades_unidade_id_idx
  on public.profissional_unidades (unidade_id);


-- ----------------------------------------------------------------------------
-- 5. RLS — mesmo padrão das tabelas que já existem
-- ----------------------------------------------------------------------------
-- A política é idêntica, palavra por palavra, à que está em `clinicas`,
-- `especialidades` e `clinica_especialidades`: quem entrou no painel lê e
-- grava, quem não entrou não faz nada. Sem `force row level security` — o
-- `force` valeria também para o dono da tabela, que é a conexão do n8n.
--
-- Os `revoke` no fim não são enfeite. A RLS filtra SELECT, INSERT, UPDATE e
-- DELETE linha a linha, mas NÃO cobre TRUNCATE: apagar a tabela inteira de
-- uma vez é permissão de tabela e passa por cima da RLS. Sem os revoke, a
-- chave pública que vai dentro do JavaScript do navegador poderia esvaziar
-- estas tabelas. Então: `anon` não pode nada, e nem o usuário logado pode
-- truncar.

alter table public.profissionais                enable row level security;
alter table public.unidades                     enable row level security;
alter table public.profissional_especialidades  enable row level security;
alter table public.profissional_unidades        enable row level security;

drop policy if exists "Autenticado le e grava" on public.profissionais;
create policy "Autenticado le e grava" on public.profissionais
  for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Autenticado le e grava" on public.unidades;
create policy "Autenticado le e grava" on public.unidades
  for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Autenticado le e grava" on public.profissional_especialidades;
create policy "Autenticado le e grava" on public.profissional_especialidades
  for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Autenticado le e grava" on public.profissional_unidades;
create policy "Autenticado le e grava" on public.profissional_unidades
  for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

revoke all on table public.profissionais               from anon;
revoke all on table public.unidades                    from anon;
revoke all on table public.profissional_especialidades from anon;
revoke all on table public.profissional_unidades       from anon;

revoke truncate on table public.profissionais               from authenticated;
revoke truncate on table public.unidades                    from authenticated;
revoke truncate on table public.profissional_especialidades from authenticated;
revoke truncate on table public.profissional_unidades       from authenticated;


-- ----------------------------------------------------------------------------
-- 6. A primeira unidade dos clientes que já existem
-- ----------------------------------------------------------------------------
-- A regra é "criar cliente cria a primeira unidade". Os clientes que já estão
-- no banco entraram antes de a regra existir, então ganham a unidade aqui —
-- com o nome do próprio cliente, que é o padrão.
--
-- Hoje isso significa uma linha, para a Clínica Teste — Helô, tratada como
-- cliente real. O `not exists` deixa o passo repetível: rodar de novo não
-- cria unidade duplicada, e não toca em quem já tem a sua.

insert into public.unidades (clinica_id, nome)
select c.id, c.nome
from public.clinicas c
where not exists (
  select 1 from public.unidades u where u.clinica_id = c.id
);


-- ----------------------------------------------------------------------------
-- 7. O gatilho: criar cliente cria a primeira unidade
-- ----------------------------------------------------------------------------
-- A regra "todo cliente tem no mínimo uma unidade" não pode depender de o
-- código do painel lembrar de cumpri-la. Se um cliente for cadastrado à mão
-- pelo editor de tabelas do Supabase, ele nasceria sem unidade — e apareceria
-- na lista de "onde atende" sem nenhuma opção para marcar. Beco sem saída.
--
-- Com o gatilho, a unidade nasce junto, não importa quem insira: painel,
-- editor de tabelas, n8n ou SQL avulso. A regra passa a ser do banco.
--
-- Este é o único ponto do arquivo que mexe em `clinicas`, e mexe no
-- comportamento, não na estrutura: nenhuma coluna é criada, alterada ou
-- removida. Nada do que já está gravado muda.
--
-- `on conflict do nothing` cobre o caso de já existir unidade com aquele nome
-- naquele cliente, e é o que torna o passo 6 e este gatilho compatíveis.
--
-- `search_path` vazio com os nomes escritos por extenso: sem isso, uma função
-- de gatilho pode ser levada a chamar a tabela errada.

create or replace function public.criar_unidade_inicial()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  insert into public.unidades (clinica_id, nome)
  values (new.id, new.nome)
  on conflict (clinica_id, nome) do nothing;
  return new;
end;
$$;

comment on function public.criar_unidade_inicial() is
  'Garante a regra: todo cliente nasce com uma unidade, com o nome do cliente.';

drop trigger if exists clinicas_cria_unidade_inicial on public.clinicas;
create trigger clinicas_cria_unidade_inicial
  after insert on public.clinicas
  for each row execute function public.criar_unidade_inicial();


-- ============================================================================
-- Confere 1: as quatro tabelas, com RLS ligada e 1 política cada.
-- ============================================================================
select c.relname        as tabela,
       c.relrowsecurity as rls_ligada,
       (select count(*) from pg_policies p
         where p.schemaname = 'public' and p.tablename = c.relname) as politicas
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relname in ('profissionais', 'unidades',
                    'profissional_especialidades', 'profissional_unidades')
order by c.relname;

-- ============================================================================
-- Confere 2: a chave pública não pode nada nas quatro. Deve vir VAZIO.
-- ============================================================================
select table_name, grantee, privilege_type
from information_schema.role_table_grants
where table_schema = 'public'
  and grantee = 'anon'
  and table_name in ('profissionais', 'unidades',
                     'profissional_especialidades', 'profissional_unidades');

-- ============================================================================
-- Confere 3: cada cliente com a sua unidade. Uma linha por cliente.
-- ============================================================================
select c.id   as cliente_id,
       c.nome as cliente,
       u.id   as unidade_id,
       u.nome as unidade
from public.clinicas c
left join public.unidades u on u.clinica_id = c.id
order by c.id, u.id;
